version: '3'

services:
  app:
    build: .
    env_file: env/app.env
    ports:
      - '3000:3000'
    networks:
      - agendamento_net
    depends_on:
      - db
  db:
    build: docker/postgres/.
    env_file:
      - env/local.pg.env
    ports:
      - '5454:5432'
    networks:
      - agendamento_net
    volumes:
      - pg_data_local:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - agendamento_net
    ports:
      - 8080:8080
volumes:
  pg_data_local:
networks:
  agendamento_net:
    driver: bridge
